title: PowerPoint with Joe
logo: /powerpoint-with-joe/assets/img/joseph-christopher.png
description: Business presentations, data storytelling, strategy and presentation design.
show_downloads: false
theme: jekyll-theme-minimal
